# Generated by Django 3.0.1 on 2020-04-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('dashboardId', models.IntegerField()),
            ],
        ),
    ]
